apps/urls.py
from django.urls import path,include
from apps.views import add_to_cart, cart_view, delete_item_from_cart, index,product_list_view,category_list_view,category_product_list_view, vendor_list_view,vendor_detail_view,product_detail_view,tag_list,search_view,checkout_view,update_cart
app_name="apps"
urlpatterns = [
    #Homepage
    path("",index,name="index"),
    #products
    path("products/", product_list_view, name="products-list"),
    path("product/<pid>", product_detail_view, name="product-detail"),

    #category
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),
    #vendor
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>", vendor_detail_view, name="vendor-detail"),
    #tags
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
    #add review

    #search
    path("search/", search_view, name="search"),

    #filterproducts

    #addtocart
    path("add-to-cart/",add_to_cart, name="add-to-cart"),
    #cart page
    path("cart/",cart_view, name="cart"),

    # delete item from cart page url
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # Update item from cart page url
    path("update-cart/", update_cart, name="update-cart"),

    # checkout
    path("checkout/", checkout_view, name="checkout"),
    # paypal 
    path("paypal/",include('paypal.standard.ipm.urls')),

]

eccom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.models import LogEntry

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.urls")),
    path("user/",include("userauths.urls")),

    path("ckeditor/",include("ckeditor_uploader.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views


app_name = "userauths"
urlpatterns = [
    path("signup/",views.register_view,name="signup"),
    path("signin/",views.login_view,name="signin"),
    path("signout/",views.logout_view,name="signout"),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Username"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password"}))

    class Meta:
        model = User 
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render,redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
User = settings.AUTH_USER_MODEL


# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, Your account was created successfully.")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1']                     
            )
            login(request, new_user)
            return redirect("apps:index")
        
        
    else:
        form = UserRegisterForm()



    context = {
        'form' : form,
    }
    return render(request,"Userauths/signup.html", context)
def login_view(request):
    if request.user.is_authenticated:
        return redirect("apps:index")
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
        except:
            messages.warning(request, f"User with {email} does not exist")

        user = authenticate(request, email=email,password=password)

        if user is not None:
            login(request, user)
            messages.success(request, "You are logged in.")
            return redirect("apps:index")
        else:
            messages.warning(request, "User Does Not Exist. Create an account.")
    context = {
    }
    return render(request, "Userauths/signin.html", context)
def logout_view(request):
    logout(request)
    messages.success(request, "You logged out.")
    return redirect("userauths:signin")

templates/userauths/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static '.\assets\css\signup-style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    {% if form.errors %}
    <div class="alert alert-danger">
      <strong>{{form.errors}}</strong>
    </div>  
    {% endif %}
    <input type="checkbox" id="flip">
    <div class="cover">
      <div class="front">
        <img src="{% static '.\assets\images\frontImg.jpg' %}" alt="">
      </div>
    </div>
    <div class="forms">
        <div class="form-content">
          <div class="login-form">
            <div class="title">Login</div>
          <form method="POST"> 
            {% csrf_token %}
            <div class="input-boxes">
              <div class="input-box">
                <i class="fas fa-envelope"></i>
                <input type="text" name="email" placeholder="Enter your email" required>
              </div>
              <div class="input-box">
                <i class="fas fa-lock"></i>
                <input type="password" name="password" placeholder="Enter your password" required>
              </div>
              <div class="text"><a href="#">Forgot password?</a></div>
              <div class="button input-box">
                <input type="submit" value="Sumbit">
              </div>
              <div class="text sign-up-text">Don't have an account? <a href="{% url "userauths:signup" %}">Signup Now</a></div>
            </div>
        </form>
      </div>
    </div>
    </div>
  </div>
</body>
</html>

templates/userauths/signup.html
{% load static %}
<!DOCTYPE html>
<!-- Created by CodingLab |www.youtube.com/c/CodingLabYT-->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <!--<title> Login and Registration Form in HTML & CSS | CodingLab </title>-->
    <link rel="stylesheet" href="{% static '.\assets\css\signup-style.css' %}">
    <!-- Fontawesome CDN Link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    {% if form.errors %}
    <div class="alert alert-danger">
      <strong>{{form.errors}}</strong>
    </div>  
    {% endif %}
    
    <input type="checkbox" id="flip">
    <div class="cover">
      <div class="front">
        <img src="{% static '.\assets\images\frontImg.jpg' %}" alt="">
      </div>
      <div class="back">
        <img class="backImg" src="{% static '.\assets\images\frontImg.jpg' %}" alt="">
      </div>
    </div>
    <div class="forms">
        <div class="form-content">
        <div class="signup-form">
          <div class="title">Signup</div>
        <form method="POST">
          {% csrf_token %}
          <div class="input-boxes">
            <div class="input-box">
              <i class="fas fa-user"></i>
              {{form.username}}
              </div>
              <div class="input-box">
                <i class="fas fa-envelope"></i>
                {{form.email}}
              </div>
              <div class="input-box">
                <i class="fas fa-lock"></i>
                {{form.password1}}
              </div>
              <div class="input-box">
                <i class="fas fa-lock"></i>
                {{form.password2}}
              </div>
              <div class="button input-box">
                <input type="submit" value="Sumbit">
              </div>
              <div class="text sign-up-text">Already have an account? <a href="{% url "userauths:signin" %}">Signin</a></div>
            </div>
      </form>
    </div>
    </div>
    </div>
  </div>
</body>
</html>