apps/urls.py
from django.urls import path,include
from apps.views import add_to_cart, cart_view, delete_item_from_cart, index,product_list_view,category_list_view,category_product_list_view, vendor_list_view,vendor_detail_view,product_detail_view,tag_list,search_view,checkout_view,update_cart
app_name="apps"
urlpatterns = [
    #Homepage
    path("",index,name="index"),
    #products
    path("products/", product_list_view, name="products-list"),
    path("product/<pid>", product_detail_view, name="product-detail"),

    #category
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),
    #vendor
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>", vendor_detail_view, name="vendor-detail"),
    #tags
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
    #add review

    #search
    path("search/", search_view, name="search"),

    #filterproducts

    #addtocart
    path("add-to-cart/",add_to_cart, name="add-to-cart"),
    #cart page
    path("cart/",cart_view, name="cart"),

    # delete item from cart page url
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # Update item from cart page url
    path("update-cart/", update_cart, name="update-cart"),

    # checkout
    path("checkout/", checkout_view, name="checkout"),
    # paypal 
    path("paypal/",include('paypal.standard.ipm.urls')),

]

eccom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.models import LogEntry

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.urls")),
    path("user/",include("userauths.urls")),

    path("ckeditor/",include("ckeditor_uploader.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/apps/cart.html
{% extends 'partials/base.html' %}
{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="{% static './assets/css/cart.css' %}">
{% endblock %}
{% block content %}
<main class="main" id="cart-list">
<div class="container">
<div class="basket">
    <div class="basket-module">
      <label for="promo-code">Welcome to cart</label>
    </div>
    <div class="basket-labels">
      <ul>
        <li class="item item-heading">Item</li>
        <li class="cart-price">Price</li>
        <li class="quantity">Quantity</li>
        <li class="subtotal">Subtotal</li>
      </ul>
    </div>
    {% if totalcartitems %}
    {% for product_id, item in cart_data.items %}
    <div class="basket-product">
      <div class="item">
        <div class="product-image">
          <img src="{{ item.image }}" alt="Placholder Image 2" class="product-frame" width="140" height="150">
        </div>
        <div class="product-details">
          <span class="item-quantity">{{item.qty}}</span> <p class="showcase-title">x {{item.title}}</p>
          <p class="showcase-desc">Navy, Size 18</p>
          <p class="showcase-desc">Product Code - 232321939</p>
        </div>
      </div>
      <div class="cart-price">{{item.price|floatformat:2}}</div>
      <div class="quantity">
        <input type="number" Placholder="Qty" value="{{item.qty}}" class="w-25 product-qty-{{ product_id }}">
      </div>
      <div class="subtotal">${% widthratio item.price 1 item.qty %}</div>
      <div class="cart-remove">
        <button class="delete-product" data-product="{{ product_id }}">Remove</button>
        <button class="update-product" data-product="{{ product_id }}">Update</button>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h2>Your cart is empty -</h2>
    <a href={% url 'apps:products-list' %} class="add-cart-btn"><h>See for products</h></a>
    {% endif %}

    
  </div>
  <aside>
    <div class="summary">
      <div class="summary-total-items"><span class="total-items"></span> Items in your Bag</div>
      <div class="summary-subtotal">
        <div class="subtotal-title">Subtotal</div>
        <div class="subtotal-value final-value" id="basket-subtotal">${{cart_total_amount}}</div>
        <div class="summary-promo hide">
          <div class="promo-title">Promotion</div>
          <div class="promo-value final-value" id="basket-promo"></div>
        </div>
      </div>
      <div class="summary-delivery">
        <select name="delivery-collection" class="summary-delivery-selection">
            <option value="0" selected="selected">Select Collection or Delivery</option>
           <option value="collection">Collection</option>
           <option value="first-class">Royal Mail 1st Class</option>
           <option value="second-class">Royal Mail 2nd Class</option>
           <option value="signed-for">Royal Mail Special Delivery</option>
        </select>
      </div>
      <div class="summary-total">
        <div class="total-title">Total</div>
        <div class="total-value final-value" id="basket-total">${{cart_total_amount}}</div>
      </div>
      <div class="summary-checkout">
        {% if totalcartitems %}
        <a href={% url 'apps:checkout' %} class="checkout-cta">Go to Secure Checkout</a>
        {% endif %}
      </div>
    </div>
</aside>
</div>
</main>
{% endblock content %}
      

templates/apps/category-list.html
{% extends 'partials/base.html' %}
{%load static%}
{% block content %}
<div class="blog">

    <div class="container">
        <h2 class="title">CATEGORIES:{{categories.count}}
        </h2>
      <div class="blog-container has-scrollbar">
        {% for c in categories %}
        <div class="blog-card">

          <a href="{% url 'apps:category-product-list' c.cid %}">
            <img src="{{c.image.url}}" alt="Clothes Retail KPIs 2021 Guide for Clothes Executives" width="300" class="blog-banner">
          </a>

          <div class="blog-content">


            <a href="{% url 'apps:category-product-list' c.cid %}">
              <h3 class="blog-title">{{c.title}}</h3>
            </a>

            <p class="blog-meta">
             <cite>{{c.category.count}}</cite>Product{{c.category.count|pluralize}}
            </p>

          </div>

        </div>
        {% endfor %}
      </div>

    </div>

  </div>

{% endblock content %}

templates/apps/category-product-list.html
{% extends 'partials/base.html' %}
{%load static%}
{% block content %}
<div class="banner">

    <div class="container">

      <div class="slider-container has-scrollbar">

        <div class="slider-item">

          <img src="{{category.image.url}}" alt="women's latest fashion sale" class="banner-img">

          <div class="banner-content">

            <p class="banner-subtitle">Category name</p>

            <h2 class="banner-title">{{category.title}}</h2>

            <p class="banner-text">
                <b>{{products.count}}</b> item{{products.count|pluralize}} for you
            </p>


          </div>

        </div>


      </div>

    </div>

  </div>
  <div class="product-main">

    <h2 class="title">New Products</h2>
    <div class="product-grid">
    
    {% for p in products %}
        <div class="showcase">

          <div class="showcase-banner">

            <img src="{{p.image.url}}" alt="Mens Winter Leathers Jackets" width="300" class="product-img default">
            <img src="{% static './assets/images/products/jacket-4.jpg' %}" alt="Mens Winter Leathers Jackets" width="300" class="product-img hover">

            <p class="showcase-badge">-{{p.get_percentage|floatformat:0}}%</p>

            <div class="showcase-actions">

              <button class="btn-action">
                <ion-icon name="heart-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="eye-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="repeat-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="bag-add-outline"></ion-icon>
              </button>

            </div>

          </div>

          <div class="showcase-content">

            <a href="#" class="showcase-category">{{p.title}}</a>

            <a href="#">
              <h3 class="showcase-title">Mens Winter Leathers Jackets</h3>
            </a>

            <div class="showcase-rating">
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star-outline"></ion-icon>
              <ion-icon name="star-outline"></ion-icon>
            </div>

            <div class="price-box">
              <p class="price">{{p.price}}</p>
              <del>{{p.old_price}}</del>
            </div>

          </div>

        </div>
      {% endfor %}
  </div>
  {% endblock content %}

templates/apps/checkout.html
{% extends 'partials/base.html' %}
{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="{% static './assets/css/checkout.css' %}">
{% endblock %}
{% block content %}
<main class="main">
<div class="row">
    <div class="col-75">
      <div class="container">
        <form action="/action_page.php">
  
          <div class="row">
            <div class="col-50">
              <h3>Billing Address</h3>
              <label for="fname"><i class="fa fa-user"></i> Full Name</label>
              <input type="text" id="fname" name="firstname" placeholder="John M. Doe">
              <label for="email"><i class="fa fa-envelope"></i> Email</label>
              <input type="text" id="email" name="email" placeholder="john@example.com">
              <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
              <input type="text" id="adr" name="address" placeholder="542 W. 15th Street">
              <label for="city"><i class="fa fa-institution"></i> City</label>
              <input type="text" id="city" name="city" placeholder="New York">
  
              <div class="row">
                <div class="col-50">
                  <label for="state">State</label>
                  <input type="text" id="state" name="state" placeholder="NY">
                </div>
                <div class="col-50">
                  <label for="zip">Zip</label>
                  <input type="text" id="zip" name="zip" placeholder="10001">
                </div>
              </div>
            </div>
  
            <div class="col-50">
              <h3>Payment</h3>
              <label for="fname">Accepted Cards</label>
              <div class="icon-container">
                <i class="fa fa-cc-visa" style="color:navy;"></i>
                <i class="fa fa-cc-amex" style="color:blue;"></i>
                <i class="fa fa-cc-mastercard" style="color:red;"></i>
                <i class="fa fa-cc-discover" style="color:orange;"></i>
              </div>
              <label for="cname">Name on Card</label>
              <input type="text" id="cname" name="cardname" placeholder="John More Doe">
              <label for="ccnum">Credit card number</label>
              <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
              <label for="expmonth">Exp Month</label>
              <input type="text" id="expmonth" name="expmonth" placeholder="September">
  
              <div class="row">
                <div class="col-50">
                  <label for="expyear">Exp Year</label>
                  <input type="text" id="expyear" name="expyear" placeholder="2018">
                </div>
                <div class="col-50">
                  <label for="cvv">CVV</label>
                  <input type="text" id="cvv" name="cvv" placeholder="352">
                </div>
              </div>
            </div>
  
          </div>
          <input type="submit" value="Continue to checkout" class="btn">
        </form>
      </div>
    </div>
  
    <div class="col-25">
      <div class="container">
        <h4>Cart
          <span class="quantity-heading" style="margin-left: 90px;">Qty</span>
          <span class="price" style="color:black">
            <i class="fa fa-shopping-cart"></i>
            <b>4</b>
          </span>
        </h4>
        {% for product_id, item in cart_data.items %}
          <div class="cart-item">
              <p><a href="{% url 'apps:product-detail' item.pid %}">{{ item.title }}</a> 
                <span class="price">{{ item.price }}</span>
                <span class="quantity">{{ item.qty }}</span>
                <span class="price">{% widthratio item.price 1 item.qty %}</span>
              </p>
          </div>
        {% endfor %}
        <hr>
        <p>Total <span class="price" style="color:black"><b>{{cart_total_amount}}</b></span></p>
        <p><a href="{% url 'apps:cart'%}">Go To cart</a> 
      </div>
    </div>
  </div>
</main>
{% endblock content %}
      

templates/apps/product-detail.html
{% extends 'partials/base.html' %}

{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="{% static './assets/css/review.css' %}">
{% endblock %}
{% block content %}


<div class="product-featured">


    <div class="showcase-wrapper has-scrollbar">

      <div class="showcase-container">

        <div class="showcase">
          
          <div class="showcase-banner">
            <img src="{{p.image.url}}" alt="shampoo, conditioner & facewash packs" class="showcase-img">
            <div id="client_logos">
              <img style="display: inline; margin: 0 5px;" onclick="#" title="heartica_logo" src="{{ p.image.url }}" alt="" width="170" height="150" />
              {% for p in p_image %}
              <img style="display: inline; margin: 0 5px;" title="heartica_logo" src="{{ p.images.url }}" alt="" width="170" height="150" />
              {% endfor %}
            </div>
          </div>


          <div class="showcase-content">
            
            <div class="showcase-rating">
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star-outline"></ion-icon>
              <ion-icon name="star-outline"></ion-icon>
            </div>

            <span>{{ average_rating.rating|floatformat }} out of 5</span>


            <p class="showcase-desc">
              {{p.description}}
            </p>

            <a href="#">
              <h3 class="showcase-title">{{p.title}}</h3>
            </a>

            <div class="price-box">
              <p class="price current-product-price-{{p.id}}">{{p.price}}</p>

              <del>{{p.old_price}}</del>
            </div>
            <!-- <div> 
            </div> -->
            
            <input type="number" value="1" name="" id="product-quantity" class="w-25 mb-10 product-quantity-{{p.id}}" style="width: 50px;">
            <br></br>
           {% comment %}  <input type="hidden" value="{{p.id}}" class="product-id" name="" id="">
            <input type="hidden" value="{{p.title}}" class="product-title" name="" id=""> {% endcomment %}
            {% comment %} <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{p.id}}"> {% endcomment %}
            <input type="hidden" class="product-pid-{{ p.id }}" value="{{ p.pid }}">
            <input type="hidden" class="product-image-{{p.id}}" value="{{p.image.url}}">
            <input type="hidden" class="product-id-{{p.id}}" value="{{ p.id }}">
            <input type="hidden" class="product-title-{{ p.id }}" value="{{ p.title }}">
            <button class="add-cart-btn add-to-cart-btn" data-index="{{p.id}}" id="add-to-cart-btn">add to cart</button>

            <div class="showcase-status">
              <div class="wrapper">
                <p>
                  already sold: <b>20</b>
                </p>

                <p>
                  available: <b>40</b>
                </p>
              </div>

              <div class="showcase-status-bar"></div>
            </div>

            <div class="countdown-box">

              <a href="#">
                <h3 class="countdown-desc">{% for tag in p.tags.all %}<a href="{% url 'apps:tags' tag.slug %}">#{{tag.name}},{% endfor %}</h3>
              </a>

            </div>
 
          </div>

        </div>

      </div>

    </div>
      <div class="testimonial-heading">
          <span>Comments({{reviews.count}})</span>
          <h4>Clients Says</h4>
      </div>
      <div class="testimonial-box-container">
        {% for r in reviews %}
          <div class="testimonial-box">
              <div class="box-top">
                  <div class="profile">
                      <div class="profile-img">
                          <img src="https://cdn.pixabay.com/photo/2017/07/18/23/23/user-2517433_1280.png" />
                      </div>
                      <div class="name-user">
                          <strong>{{r.user.username|title}}</strong>
                          <span>@liammendes</span>
                          <span>{{r.date|date:"d M, Y"}}</span>
                      </div>
                  </div>
                  <div class="reviews">
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="far fa-star"></i>
                  </div>
              </div>
              <div class="client-comment">
                  <p>{{r.review}}</p>
              </div>
          </div>
        {% endfor %}
      </div>
  
  </div>
  {% endblock content %}
      

templates/apps/products-list.html
{% extends 'partials/base.html' %}
{%load static%}
{% block content %}

<div class="product-main">

  <h2 class="title">New Products</h2>
  <div class="product-grid">
  
    {% for p in products %}
    <div class="showcase">

      <div class="showcase-banner">

        <img src="{{p.image.url}}" alt="Mens Winter Leathers Jackets" width="300" class="product-img default">
        <img src="{% static './assets/images/products/jacket-4.jpg' %}" alt="Mens Winter Leathers Jackets" width="300" class="product-img hover">

        <p class="showcase-badge">-{{p.get_percentage|floatformat:0}}%</p>

        <div class="showcase-actions">

          <button class="btn-action">
            <ion-icon name="heart-outline"></ion-icon>
          </button>

          <button class="btn-action">
            <ion-icon name="eye-outline"></ion-icon>
          </button>

          <button class="btn-action">
            <ion-icon name="repeat-outline"></ion-icon>
          </button>

          <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{p.id}}">
          <input type="hidden" class="product-pid-{{ p.id }}" value="{{ p.pid }}">
          <input type="hidden" class="product-image-{{p.id}}" value="{{p.image.url}}">
          <input type="hidden" class="product-id-{{p.id}}" value="{{ p.id }}">
          <input type="hidden" class="product-title-{{ p.id }}" value="{{ p.title }}">
          <button class="btn-action add-to-cart-btn" data-index="{{ p.id }}" id="add-to-cart-btn">
          <ion-icon name="bag-add-outline"></ion-icon>
          </button>

        </div>

      </div>

      <div class="showcase-content">

        <a href="{% url 'apps:product-detail' p.pid %}" class="showcase-category">{{p.title}}</a>

        <a href="#">
          <h3 class="showcase-title">Mens Winter Leathers Jackets</h3>
        </a>

        <div class="showcase-rating">
          <ion-icon name="star"></ion-icon>
          <ion-icon name="star"></ion-icon>
          <ion-icon name="star"></ion-icon>
          <ion-icon name="star-outline"></ion-icon>
          <ion-icon name="star-outline"></ion-icon>
        </div>

        <div class="price-box">
          <p class="price current-product-price-{{p.id}}">{{p.price}}</p>
          <del>{{p.old_price}}</del>
        </div>

      </div>

    </div>
  {% endfor %}
</div>
{% endblock content %}

templates/apps/search.html
{% extends 'partials/base.html' %}
{%load static%}
{% block content %}
<div class="banner">

    <div class="container">

      <div class="slider-container has-scrollbar">

        <div class="slider-item">

          <img src="{% static './assets/images/search-banner.jpg' %}" alt="women's latest fashion sale" class="banner-img">

          <div class="banner-content">

            <p class="banner-subtitle">Searched content</p>

            <h2 class="banner-title">{{query}}</h2>

            <p class="banner-text">
                <b>{{products.count}}</b> item{{products.count|pluralize}} for you
            </p>


          </div>

        </div>


      </div>

    </div>

  </div>
  <div class="product-main">

    <h2 class="title">New Products</h2>
    <div class="product-grid">
    
    {% for p in products %}
        <div class="showcase">

          <div class="showcase-banner">

            <img src="{{p.image.url}}" alt="Mens Winter Leathers Jackets" width="300" class="product-img default">
            <img src="{% static './assets/images/products/jacket-4.jpg' %}" alt="Mens Winter Leathers Jackets" width="300" class="product-img hover">

            <p class="showcase-badge">-{{p.get_percentage|floatformat:0}}%</p>

            <div class="showcase-actions">

              <button class="btn-action">
                <ion-icon name="heart-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="eye-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="repeat-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="bag-add-outline"></ion-icon>
              </button>

            </div>

          </div>

          <div class="showcase-content">

            <a href="#" class="showcase-category">{{p.title}}</a>

            <a href="#">
              <h3 class="showcase-title">Mens Winter Leathers Jackets</h3>
            </a>

            <div class="showcase-rating">
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star-outline"></ion-icon>
              <ion-icon name="star-outline"></ion-icon>
            </div>

            <div class="price-box">
              <p class="price">{{p.price}}</p>
              <del>{{p.old_price}}</del>
            </div>

          </div>

        </div>
      {% endfor %}
  </div>
  {% endblock content %}

templates/apps/tag.html
{% extends 'partials/base.html' %}
{%load static%}
{% block content %}
<div class="banner">

    <div class="container">

      <div class="slider-container has-scrollbar">

        <div class="slider-item">

          <img src="{{category.image.url}}" alt="women's latest fashion sale" class="banner-img">

          <div class="banner-content">

            <p class="banner-subtitle">Category name</p>

            <h2 class="banner-title">{{tag.name}}</h2>

            <p class="banner-text">
                <b>{{products.count}}</b> item{{products.count|pluralize}} for you
            </p>


          </div>

        </div>


      </div>

    </div>

  </div>
  <div class="product-main">

    <h2 class="title">New Products</h2>
    <div class="product-grid">
    
    {% for p in products %}
        <div class="showcase">

          <div class="showcase-banner">

            <img src="{{p.image.url}}" alt="Mens Winter Leathers Jackets" width="300" class="product-img default">
            <img src="{% static './assets/images/products/jacket-4.jpg' %}" alt="Mens Winter Leathers Jackets" width="300" class="product-img hover">

            <p class="showcase-badge">-{{p.get_percentage|floatformat:0}}%</p>

            <div class="showcase-actions">

              <button class="btn-action">
                <ion-icon name="heart-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="eye-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="repeat-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="bag-add-outline"></ion-icon>
              </button>

            </div>

          </div>

          <div class="showcase-content">

            <a href="{% url 'apps:product-detail' p.pid %}" class="showcase-category">{{p.title}}</a>

            <a href="{% url 'apps:product-detail' p.pid %}">
              <h3 class="showcase-title">Mens Winter Leathers Jackets</h3>
            </a>

            <div class="showcase-rating">
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star-outline"></ion-icon>
              <ion-icon name="star-outline"></ion-icon>
            </div>

            <div class="price-box">
              <p class="price">{{p.price}}</p>
              <del>{{p.old_price}}</del>
            </div>

          </div>

        </div>
      {% endfor %}
  </div>
  {% endblock content %}

templates/apps/vendor-detail.html
{% extends 'partials/base.html' %}
{%load static%}
{% block content %}
<div class="banner">

    <div class="container">

      <div class="slider-container has-scrollbar">

        <div class="slider-item">

          <img src="{{vendor.image.url}}" alt="" class="banner-img">

          <div class="banner-content">

            <p class="banner-subtitle">Vendor name</p>

            <h2 class="banner-title">{{vendor.title}}</h2>

            <p class="banner-text">
                <b>{{products.count}}</b> item{{products.count|pluralize}} for you
            </p>


          </div>

        </div>


      </div>

    </div>

  </div>
  <div class="product-main">

    <h2 class="title">New Products</h2>
    <div class="product-grid">
    
    {% for p in products %}
        <div class="showcase">

          <div class="showcase-banner">

            <img src="{{p.image.url}}" alt="Mens Winter Leathers Jackets" width="300" class="product-img default">
            <img src="{% static './assets/images/products/jacket-4.jpg' %}" alt="Mens Winter Leathers Jackets" width="300" class="product-img hover">

            <p class="showcase-badge">-{{p.get_percentage|floatformat:0}}%</p>

            <div class="showcase-actions">

              <button class="btn-action">
                <ion-icon name="heart-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="eye-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="repeat-outline"></ion-icon>
              </button>

              <button class="btn-action">
                <ion-icon name="bag-add-outline"></ion-icon>
              </button>

            </div>

          </div>

          <div class="showcase-content">

            <a href="#" class="showcase-category">{{p.title}}</a>

            <a href="#">
              <h3 class="showcase-title">Mens Winter Leathers Jackets</h3>
            </a>

            <div class="showcase-rating">
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star"></ion-icon>
              <ion-icon name="star-outline"></ion-icon>
              <ion-icon name="star-outline"></ion-icon>
            </div>

            <div class="price-box">
              <p class="price">{{p.price}}</p>
              <del>{{p.old_price}}</del>
            </div>

          </div>

        </div>
      {% endfor %}
  </div>
  {% endblock content %}

templates/apps/vendor-list.html
{% extends 'partials/base.html' %}
{%load static%}
{% block content %}
<div class="product-featured">

    <h2 class="title">-----------------------------------------------------------VENDOR LIST----------------------------------------------------------------</h2>
    <div class="showcase-wrapper has-scrollbar">
    {% for v in vendors %}
      <div class="showcase-container">

        <div class="showcase">
          
          <div class="showcase-banner">
            <img src="{{v.image.url}}" alt="ASUS" class="showcase-img">
          </div>

          <div class="showcase-content">
            
            <a href="{% url 'apps:vendor-detail'  v.vid %}">
              <h3 class="showcase-title">{{v.title}}</h3>
            </a>
            <p class="showcase-desc">
                Adress:{{v.address}}
              </p>
            <p class="blog-meta">
                Since {{v.date|date:"Y"}}
            </p>

            <div class="price-box">
              <p class="price">{{v.product.all.count}}Product{{v.products.all.count|pluralize}}</p>
            </div>


            <div class="countdown-box">


           

            </div>

          </div>

        </div>

      </div>
    {% endfor %}
    </div>

  </div>
{% endblock content %}